const TYPE = {
    MINED: "MINED",
    ADD_NEW_BLOCK_ADD: "ADD_NEW_BLOCK",
    SEND_TRANSACTION: "SEND_TRANSACTION",
    NEW_TRANSACTION: "NEW_TRANSACTION",
    START_MINING: "START_MINING",
    MINING_A_BLOCK: "MINING_A_BLOCK",
    LOGIN: "LOGIN",
    LAST_BLOCK: "LAST_BLOCK",
    VOTE_NEW_BLOCK: "VOTE_NEW_BLOCK",
    GET_BALANCE: "GET_BALANCE",
  };
  
  export default TYPE;
  